### PR TITLE
Adds Github Code Scanning (CodeQL) 

### PR DESCRIPTION
**Pull request by AlexandruAntonescuKeysight**
## Summary
This PR adds a workflow which enables Github Code Scanning (the engine used is CodeQL).
It provides a suite of security queries that are run on every push and pull request on main branch. The results are visible in the security tab. This also represents a check in a PR context.
The scan is being done on python and C++ code (the C++ code needs a build step; I've built et_feeder as shared lib).

Example (the errors also appear as comments in the PR):

image

## Test Plan
The testing was done by adding known bad lines of code to see if the problems are identified. An example could be seen in the picture above.

### CODE REVIEW

**Comment by TaekyungHeo** [comment]
Thanks, @AlexandruAntonescuKeysight. Do we need to update the paths as shown in "fixes include paths in the feeder after directory refactor"? Can you handle this in the YAML file instead? I would like to avoid changing the include path in the feeder. I assume someone uses it by adding the feeder directory as an include path. It also does not seem natural to have an include path starting with 'src,' at least for me.

**Comment by TaekyungHeo** [comment]
+ This will break downstream tools because the include path has been updated.

**Comment by danmih-ixia** [comment]
since the files have been moved from "et_feeder" to "src/feeder", the "et_feeder/et_feeder.h" paths are currently broken so need to be fixed. I think we should use #include "et_feeder.h" and add the include path as parameter at compile time.

**Comment by TaekyungHeo** [comment]
Yes, it makes sense. Please review and comment, @srinivas212

**Comment by srinivas212** [comment]
@AlexandruAntonescuKeysight  @danmih-ixia @TaekyungHeo  - are there any other opens? The paths issue has been fixed.

**Comment by danmih-ixia** [comment]
> @AlexandruAntonescuKeysight @danmih-ixia @TaekyungHeo - are there any other opens? The paths issue has been fixed.

I don't think there is anything pending. The path issue has been submitted now, please check.

**Review by srinivas212 — APPROVED** [review]

**Pull request merged**
