### PR TITLE
Remove num_dims and involved_dim

### PR DESCRIPTION
**Pull request by TaekyungHeo**
## Summary
Removed num_dims and involved_dim as they are ASTRA-sim specific.

## Test Plan
```
$ pip install .
$ python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename ~/rank0.json --output_filename ~/rank0.chakra
$ python3 -m chakra.et_converter.et_converter --input_type Text --input_filename ~/astra-sim/inputs/workload/ASTRA-sim-1.0/MLP_ModelParallel.txt --output_filename ~/rank0.chakra --num_npus 1 --num_passes
 10
$ python -m chakra.et_generator.et_generator
```

### CODE REVIEW

**Comment by JoongunPark** [comment]
1. We've observed current ASTRA-SIM terminates with SEGSEV while running Llama trace with the lastest Chakra version. 
The error was occurred since `involved_dim` is empty (0) in the Chakra node. Which means even before this PR, `involved_dim` is not set properly. This change seems to solve this problem. 

2. Could you let me know why you think `num_dims `and `involved_dim` are ASTRA-Sim specific and no longer required in Chakra?
What were their original role in Chakra?

**Comment by TaekyungHeo** [comment]
Hi @JoongunPark ,

num_dims and involved_dims were introduced in Chakra solely for ASTRA-sim compatibility. They do not serve any role within the Chakra toolchains themselves; their inclusion was specifically to accommodate ASTRA-sim. We decided to remove involved_dim and num_dims because our goal is for Chakra to focus on universal features that are applicable across all toolchains. For a comprehensive understanding of the roles of num_dims and involved_dims within ASTRA-sim, I recommend reaching out directly to the ASTRA-sim maintainers, such as Saeed.

As a suggestion, consider creating a fork of Chakra for ASTRA-sim under the ASTRA-sim group. This approach would allow you to revert the changes concerning num_dims and involved_dim to maintain compatibility with ASTRA-sim. We believe that simulator-specific modifications should be managed in this manner, rather than making updates to the common Chakra toolchains that affect their universal applicability.

**Comment by JoongunPark** [comment]
> Hi @JoongunPark ,
> 
> num_dims and involved_dims were introduced in Chakra solely for ASTRA-sim compatibility. They do not serve any role within the Chakra toolchains themselves; their inclusion was specifically to accommodate ASTRA-sim. We decided to remove involved_dim and num_dims because our goal is for Chakra to focus on universal features that are applicable across all toolchains. For a comprehensive understanding of the roles of num_dims and involved_dims within ASTRA-sim, I recommend reaching out directly to the ASTRA-sim maintainers, such as Saeed.
> 
> As a suggestion, consider creating a fork of Chakra for ASTRA-sim under the ASTRA-sim group. This approach would allow you to revert the changes concerning num_dims and involved_dim to maintain compatibility with ASTRA-sim. We believe that simulator-specific modifications should be managed in this manner, rather than making updates to the common Chakra toolchains that affect their universal applicability.

Got it. Thank you!

**Comment by srinivas212** [comment]
Merging after meeting today w/ @TaekyungHeo, Jinsun@GaTech and team.

**Review by srinivas212 — APPROVED** [review]

**Pull request merged**
